# The name of the current user and basic details for the user's top 3 repos.
query PopularRepos {
    viewer {
        login
        repositories(
            first: 3
            ownerAffiliations: OWNER
            privacy: PUBLIC
            orderBy: { field: STARGAZERS, direction: DESC }
        ) {
            nodes {
                name
                description
                stargazers {
                    totalCount
                }
            }
        }
    }
}
